version: "3.8"
services:
  postgres:
    image: postgres:15-alpine
    container_name: cloudops-postgres
    environment:
      POSTGRES_DB: cloudops
      POSTGRES_USER: cloudops
      POSTGRES_PASSWORD: cloudops123
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U cloudops -d cloudops"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - cloudops-network
  redis:
    image: redis:7-alpine
    container_name: cloudops-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD","redis-cli","ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - cloudops-network
  api:
    build:
      context: ../apps/api
      dockerfile: Dockerfile
    container_name: cloudops-api
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: cloudops
      DB_USER: cloudops
      DB_PASSWORD: cloudops123
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:3000/health || exit 1"]
      interval: 30s
      timeout: 3s 
      retries: 3
      start_period: 5s
    networks:
      - cloudops-network
volumes:
   postgres-data:

networks:
  cloudops-network:
    driver: bridge